# this is a container for running pycharm apps against tensorforce from
FROM ubuntu:xenial
RUN apt-get update -y
RUN apt-get install -y --no-install-recommends tzdata python3 python3-dev python3-pip python3-setuptools git dos2unix net-tools iproute2 iputils-ping telnet
RUN apt-get install -y python3-setuptools --upgrade
RUN apt-get install -y build-essential
RUN pip3 install wheel numpy msgpack msgpack-numpy pydevd tensorflow tensorforce dm-sonnet jupyter notebook cached_property scipy cython matplotlib pygame msgpack-python pillow virtualenv virtualenvwrapper python-dateutil gym gym[atari]

CMD ["bash"]
